export default {
  "login": "salao45",
  "id": 64453479,
  "node_id": "MDQ6VXNlcjY0NDUzNDc5",
  "avatar_url": "https://avatars.githubusercontent.com/u/64453479?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/salao45",
  "html_url": "https://github.com/salao45",
  "followers_url": "https://api.github.com/users/salao45/followers",
  "following_url": "https://api.github.com/users/salao45/following{/other_user}",
  "gists_url": "https://api.github.com/users/salao45/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/salao45/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/salao45/subscriptions",
  "organizations_url": "https://api.github.com/users/salao45/orgs",
  "repos_url": "https://api.github.com/users/salao45/repos",
  "events_url": "https://api.github.com/users/salao45/events{/privacy}",
  "received_events_url": "https://api.github.com/users/salao45/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Saurav Kumar",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 6,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2020-04-28T03:36:47Z",
  "updated_at": "2023-12-27T09:54:44Z"
}